package com.mazidul.questions.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Entity  // Marks this class as a JPA entity mapped to a database table.
@Data  // Lombok annotation to automatically generate getters, setters, toString, equals, and hashCode methods.
//@AllArgsConstructor  // Lombok annotation to generate a constructor with all fields as parameters.
//@NoArgsConstructor  // Lombok annotation to generate a default no-arguments constructor.
public class Question {

    @Id  // Specifies the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.SEQUENCE)  // Configures the ID to be generated using a sequence strategy.
    private Integer id;
    private String questionTitle;  // The title or text of the question.
    private String option1;  // The first option for the question.
    private String option2;  // The second option for the question.
    private String option3;  // The third option for the question.
    private String option4;  // The fourth option for the question.
    private String rightAnswer;  // The correct answer for the question.
    private String difficultyLevel;  // The difficulty level of the question (e.g., easy, medium, hard).
    private String category;  // The category to which the question belongs.

    // Default no-argument constructor. Required for JPA.
    public Question() {
    }

    // Constructor with all fields as parameters. Useful for creating instances manually.
    public Question(Integer id, String questionTitle, String option1, String option2, String option3, String option4, String rightAnswer, String difficultyLevel, String category) {
        this.id = id;
        this.questionTitle = questionTitle;
        this.option1 = option1;
        this.option2 = option2;
        this.option3 = option3;
        this.option4 = option4;
        this.rightAnswer = rightAnswer;
        this.difficultyLevel = difficultyLevel;
        this.category = category;
    }

    // Getters and setters for each field (automatically generated by Lombok's @Data annotation).
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getQuestionTitle() {
        return questionTitle;
    }

    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }

    public String getOption1() {
        return option1;
    }

    public void setOption1(String option1) {
        this.option1 = option1;
    }

    public String getOption2() {
        return option2;
    }

    public void setOption2(String option2) {
        this.option2 = option2;
    }

    public String getOption3() {
        return option3;
    }

    public void setOption3(String option3) {
        this.option3 = option3;
    }

    public String getOption4() {
        return option4;
    }

    public void setOption4(String option4) {
        this.option4 = option4;
    }

    public String getRightAnswer() {
        return rightAnswer;
    }

    public void setRightAnswer(String rightAnswer) {
        this.rightAnswer = rightAnswer;
    }

    public String getDifficultyLevel() {
        return difficultyLevel;
    }

    public void setDifficultyLevel(String difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}
