package com.mazidul.quiz.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

@Entity // Marks this class as a JPA entity, meaning it will be mapped to a database table
@Data // Lombok annotation to automatically generate getters, setters, toString, equals, and hashCode methods
public class Quiz {

    @Id // Denotes that this field is the primary key for the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key will be auto-generated
    private Integer id; // Quiz ID (primary key)

    private String title; // The title of the quiz

    @ElementCollection // Specifies that this field will be a collection of elements (list of integers, in this case)
    private List<Integer> questionsIds; // List of question IDs associated with this quiz

    // Default constructor
    public Quiz() {
    }

    // Constructor with all fields for initializing the quiz object
    public Quiz(Integer id, String title, List<Integer> questionsIds) {
        this.id = id;
        this.title = title;
        this.questionsIds = questionsIds;
    }

    // Getters and Setters (These are automatically generated by Lombok due to the @Data annotation, but you can keep them if needed)

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Integer> getQuestions() {
        return questionsIds;
    }

    public void setQuestions(List<Integer> questionsIds) {
        this.questionsIds = questionsIds;
    }
}
