package com.mazidul.quiz.model;

import lombok.Data;

@Data // Lombok annotation to automatically generate getters, setters, toString, equals, and hashCode methods
public class Response {

    private Integer id; // The ID of the question for which the response is provided
    private String response; // The response to the question (e.g., answer option chosen by the user)

    // Default constructor
    public Response() {
    }

    // Constructor with all fields for initializing the response object
    public Response(Integer id, String response) {
        this.id = id;
        this.response = response;
    }

    // Getters and Setters (These are automatically generated by Lombok due to the @Data annotation, but you can keep them if needed)

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }
}
