package com.mazidul.quiz.model;

import lombok.Data;

@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods automatically
public class QuestionWrapper {

    private Integer id; // Question ID
    private String questionTitle; // The question text
    private String option1; // Option 1 for the question
    private String option2; // Option 2 for the question
    private String option3; // Option 3 for the question
    private String option4; // Option 4 for the question

    // Constructor to initialize the question details
    public QuestionWrapper(Integer id, String questionTitle, String option1, String option2, String option3, String option4) {
        this.id = id;
        this.questionTitle = questionTitle;
        this.option1 = option1;
        this.option2 = option2;
        this.option3 = option3;
        this.option4 = option4;
    }

    // Getters and Setters (These are automatically generated by Lombok due to the @Data annotation, but you can keep them if needed)

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getQuestionTitle() {
        return questionTitle;
    }

    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }

    public String getOption1() {
        return option1;
    }

    public void setOption1(String option1) {
        this.option1 = option1;
    }

    public String getOption2() {
        return option2;
    }

    public void setOption2(String option2) {
        this.option2 = option2;
    }

    public String getOption3() {
        return option3;
    }

    public void setOption3(String option3) {
        this.option3 = option3;
    }

    public String getOption4() {
        return option4;
    }

    public void setOption4(String option4) {
        this.option4 = option4;
    }
}
